### ISSUE TITLE
Want to know how many hours you spend when you train the model with t=6,cw on resnet18 on CIFAR10 on your GPU

### ISSUE THREAD

**Issue by MuscleGood** [Ikarosy/Gated-LIF#1]
Hi, I want to know how many hours you spend when you train the model with t=6,cw on resnet18 on CIFAR10 on your GPU.

Thank you for the code, expecting for your reply, thank you in advance!

**Comment by Ikarosy** [comment]
On average, it takes around 396 sec., which is recorded in the training log, for an iteration (one epoch of training + one epoch of testing) on a single A100 card.  I did not precisely record the time cost for completely training a resnet18 on cifar10.  But I guess we can speculate the time cost is about 22 hours (396 * 200 / 60 / 60).  The training may cost slightly more time in my practice due to the server's performance.

**Comment by MuscleGood** [comment]
OK I got it, thanks a lot for the reply!!

**Comment by Ikarosy** [comment]
You are welcome to ask any questions.
